/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import type * as Schemas from './xatabaseSchemas';

export type SimpleError = {
  id?: string;
  message: string;
  status: number;
};

export type BadRequestError = {
  id?: string;
  message: string;
  status: number;
};

/**
 * @example {"status":401,"message":"invalid API key"}
 */
export type AuthError = {
  id?: string;
  message: string;
  status: number;
};

export type BranchMigrationPlan = {
  version: number;
  migration: Schemas.BranchMigration;
};

export type QueryResponse = {
  records: Schemas.XataRecord[];
  meta: Schemas.RecordsMetadata;
};

export type SearchResponse = {
  records: Schemas.XataRecord[];
};

/**
 * @example {"migrationID":"mig_c7m19ilcefoebpqj12p0"}
 */
export type MigrationIdResponse = {
  /*
   * @minLength 1
   */
  migrationID: string;
};
