/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type BadRequestError = {
  id?: string;
  message: string;
};

/**
 * @example {"message":"invalid API key"}
 */
export type AuthError = {
  id?: string;
  message: string;
};

export type SimpleError = {
  id?: string;
  message: string;
};
