/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import type * as Fetcher from './controlPlaneFetcher';
import { controlPlaneFetch, ControlPlaneFetcherExtraProps } from './controlPlaneFetcher';
import type * as Schemas from './controlPlaneSchemas';
import type * as Responses from './controlPlaneResponses';

export type GetUserError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type GetUserVariables = ControlPlaneFetcherExtraProps;

/**
 * Return details of the user making the request
 */
export const getUser = (variables: GetUserVariables, signal?: AbortSignal) =>
  controlPlaneFetch<Schemas.UserWithID, GetUserError, undefined, {}, {}, {}>({
    url: '/user',
    method: 'get',
    ...variables,
    signal
  });

export type UpdateUserError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type UpdateUserVariables = {
  body: Schemas.User;
} & ControlPlaneFetcherExtraProps;

/**
 * Update user info
 */
export const updateUser = (variables: UpdateUserVariables, signal?: AbortSignal) =>
  controlPlaneFetch<Schemas.UserWithID, UpdateUserError, Schemas.User, {}, {}, {}>({
    url: '/user',
    method: 'put',
    ...variables,
    signal
  });

export type DeleteUserError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type DeleteUserVariables = ControlPlaneFetcherExtraProps;

/**
 * Delete the user making the request
 */
export const deleteUser = (variables: DeleteUserVariables, signal?: AbortSignal) =>
  controlPlaneFetch<undefined, DeleteUserError, undefined, {}, {}, {}>({
    url: '/user',
    method: 'delete',
    ...variables,
    signal
  });

export type GetUserAPIKeysError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type GetUserAPIKeysResponse = {
  keys: {
    name: string;
    createdAt: Schemas.DateTime;
  }[];
};

export type GetUserAPIKeysVariables = ControlPlaneFetcherExtraProps;

/**
 * Retrieve a list of existing user API keys
 */
export const getUserAPIKeys = (variables: GetUserAPIKeysVariables, signal?: AbortSignal) =>
  controlPlaneFetch<GetUserAPIKeysResponse, GetUserAPIKeysError, undefined, {}, {}, {}>({
    url: '/user/keys',
    method: 'get',
    ...variables,
    signal
  });

export type CreateUserAPIKeyPathParams = {
  /**
   * API Key name
   */
  keyName: Schemas.APIKeyName;
};

export type CreateUserAPIKeyError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type CreateUserAPIKeyResponse = {
  name: string;
  key: string;
  createdAt: Schemas.DateTime;
};

export type CreateUserAPIKeyVariables = {
  pathParams: CreateUserAPIKeyPathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Create and return new API key
 */
export const createUserAPIKey = (variables: CreateUserAPIKeyVariables, signal?: AbortSignal) =>
  controlPlaneFetch<CreateUserAPIKeyResponse, CreateUserAPIKeyError, undefined, {}, {}, CreateUserAPIKeyPathParams>({
    url: '/user/keys/{keyName}',
    method: 'post',
    ...variables,
    signal
  });

export type DeleteUserAPIKeyPathParams = {
  /**
   * API Key name
   */
  keyName: Schemas.APIKeyName;
};

export type DeleteUserAPIKeyError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type DeleteUserAPIKeyVariables = {
  pathParams: DeleteUserAPIKeyPathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Delete an existing API key
 */
export const deleteUserAPIKey = (variables: DeleteUserAPIKeyVariables, signal?: AbortSignal) =>
  controlPlaneFetch<undefined, DeleteUserAPIKeyError, undefined, {}, {}, DeleteUserAPIKeyPathParams>({
    url: '/user/keys/{keyName}',
    method: 'delete',
    ...variables,
    signal
  });

export type GetWorkspacesListError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type GetWorkspacesListResponse = {
  workspaces: {
    id: Schemas.WorkspaceID;
    name: string;
    slug: string;
    role: Schemas.Role;
  }[];
};

export type GetWorkspacesListVariables = ControlPlaneFetcherExtraProps;

/**
 * Retrieve the list of workspaces the user belongs to
 */
export const getWorkspacesList = (variables: GetWorkspacesListVariables, signal?: AbortSignal) =>
  controlPlaneFetch<GetWorkspacesListResponse, GetWorkspacesListError, undefined, {}, {}, {}>({
    url: '/workspaces',
    method: 'get',
    ...variables,
    signal
  });

export type CreateWorkspaceError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type CreateWorkspaceVariables = {
  body: Schemas.WorkspaceMeta;
} & ControlPlaneFetcherExtraProps;

/**
 * Creates a new workspace with the user requesting it as its single owner.
 */
export const createWorkspace = (variables: CreateWorkspaceVariables, signal?: AbortSignal) =>
  controlPlaneFetch<Schemas.Workspace, CreateWorkspaceError, Schemas.WorkspaceMeta, {}, {}, {}>({
    url: '/workspaces',
    method: 'post',
    ...variables,
    signal
  });

export type GetWorkspacePathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
};

export type GetWorkspaceError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type GetWorkspaceVariables = {
  pathParams: GetWorkspacePathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Retrieve workspace info from a workspace ID
 */
export const getWorkspace = (variables: GetWorkspaceVariables, signal?: AbortSignal) =>
  controlPlaneFetch<Schemas.Workspace, GetWorkspaceError, undefined, {}, {}, GetWorkspacePathParams>({
    url: '/workspaces/{workspaceId}',
    method: 'get',
    ...variables,
    signal
  });

export type UpdateWorkspacePathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
};

export type UpdateWorkspaceError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type UpdateWorkspaceVariables = {
  body: Schemas.WorkspaceMeta;
  pathParams: UpdateWorkspacePathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Update workspace info
 */
export const updateWorkspace = (variables: UpdateWorkspaceVariables, signal?: AbortSignal) =>
  controlPlaneFetch<Schemas.Workspace, UpdateWorkspaceError, Schemas.WorkspaceMeta, {}, {}, UpdateWorkspacePathParams>({
    url: '/workspaces/{workspaceId}',
    method: 'put',
    ...variables,
    signal
  });

export type DeleteWorkspacePathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
};

export type DeleteWorkspaceError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type DeleteWorkspaceVariables = {
  pathParams: DeleteWorkspacePathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Delete the workspace with the provided ID
 */
export const deleteWorkspace = (variables: DeleteWorkspaceVariables, signal?: AbortSignal) =>
  controlPlaneFetch<undefined, DeleteWorkspaceError, undefined, {}, {}, DeleteWorkspacePathParams>({
    url: '/workspaces/{workspaceId}',
    method: 'delete',
    ...variables,
    signal
  });

export type GetWorkspaceMembersListPathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
};

export type GetWorkspaceMembersListError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type GetWorkspaceMembersListVariables = {
  pathParams: GetWorkspaceMembersListPathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Retrieve the list of members of the given workspace
 */
export const getWorkspaceMembersList = (variables: GetWorkspaceMembersListVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    Schemas.WorkspaceMembers,
    GetWorkspaceMembersListError,
    undefined,
    {},
    {},
    GetWorkspaceMembersListPathParams
  >({ url: '/workspaces/{workspaceId}/members', method: 'get', ...variables, signal });

export type UpdateWorkspaceMemberRolePathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
  /**
   * UserID
   */
  userId: Schemas.UserID;
};

export type UpdateWorkspaceMemberRoleError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type UpdateWorkspaceMemberRoleRequestBody = {
  role: Schemas.Role;
};

export type UpdateWorkspaceMemberRoleVariables = {
  body: UpdateWorkspaceMemberRoleRequestBody;
  pathParams: UpdateWorkspaceMemberRolePathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Update a workspace member role. Workspaces must always have at least one owner, so this operation will fail if trying to remove owner role from the last owner in the workspace.
 */
export const updateWorkspaceMemberRole = (variables: UpdateWorkspaceMemberRoleVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    undefined,
    UpdateWorkspaceMemberRoleError,
    UpdateWorkspaceMemberRoleRequestBody,
    {},
    {},
    UpdateWorkspaceMemberRolePathParams
  >({ url: '/workspaces/{workspaceId}/members/{userId}', method: 'put', ...variables, signal });

export type RemoveWorkspaceMemberPathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
  /**
   * UserID
   */
  userId: Schemas.UserID;
};

export type RemoveWorkspaceMemberError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type RemoveWorkspaceMemberVariables = {
  pathParams: RemoveWorkspaceMemberPathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Remove the member from the workspace
 */
export const removeWorkspaceMember = (variables: RemoveWorkspaceMemberVariables, signal?: AbortSignal) =>
  controlPlaneFetch<undefined, RemoveWorkspaceMemberError, undefined, {}, {}, RemoveWorkspaceMemberPathParams>({
    url: '/workspaces/{workspaceId}/members/{userId}',
    method: 'delete',
    ...variables,
    signal
  });

export type InviteWorkspaceMemberPathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
};

export type InviteWorkspaceMemberError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
  | {
      status: 409;
      payload: Responses.SimpleError;
    }
>;

export type InviteWorkspaceMemberRequestBody = {
  /**
   * @format email
   */
  email: string;
  role: Schemas.Role;
};

export type InviteWorkspaceMemberVariables = {
  body: InviteWorkspaceMemberRequestBody;
  pathParams: InviteWorkspaceMemberPathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Invite some user to join the workspace with the given role
 */
export const inviteWorkspaceMember = (variables: InviteWorkspaceMemberVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    Schemas.WorkspaceInvite,
    InviteWorkspaceMemberError,
    InviteWorkspaceMemberRequestBody,
    {},
    {},
    InviteWorkspaceMemberPathParams
  >({ url: '/workspaces/{workspaceId}/invites', method: 'post', ...variables, signal });

export type UpdateWorkspaceMemberInvitePathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
  /**
   * Invite identifier
   */
  inviteId: Schemas.InviteID;
};

export type UpdateWorkspaceMemberInviteError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
  | {
      status: 422;
      payload: Responses.SimpleError;
    }
>;

export type UpdateWorkspaceMemberInviteRequestBody = {
  role: Schemas.Role;
};

export type UpdateWorkspaceMemberInviteVariables = {
  body: UpdateWorkspaceMemberInviteRequestBody;
  pathParams: UpdateWorkspaceMemberInvitePathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * This operation provides a way to update an existing invite. Updates are performed in-place; they do not change the invite link, the expiry time, nor do they re-notify the recipient of the invite.
 */
export const updateWorkspaceMemberInvite = (variables: UpdateWorkspaceMemberInviteVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    Schemas.WorkspaceInvite,
    UpdateWorkspaceMemberInviteError,
    UpdateWorkspaceMemberInviteRequestBody,
    {},
    {},
    UpdateWorkspaceMemberInvitePathParams
  >({ url: '/workspaces/{workspaceId}/invites/{inviteId}', method: 'patch', ...variables, signal });

export type CancelWorkspaceMemberInvitePathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
  /**
   * Invite identifier
   */
  inviteId: Schemas.InviteID;
};

export type CancelWorkspaceMemberInviteError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type CancelWorkspaceMemberInviteVariables = {
  pathParams: CancelWorkspaceMemberInvitePathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * This operation provides a way to cancel invites by deleting them. Already accepted invites cannot be deleted.
 */
export const cancelWorkspaceMemberInvite = (variables: CancelWorkspaceMemberInviteVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    undefined,
    CancelWorkspaceMemberInviteError,
    undefined,
    {},
    {},
    CancelWorkspaceMemberInvitePathParams
  >({ url: '/workspaces/{workspaceId}/invites/{inviteId}', method: 'delete', ...variables, signal });

export type AcceptWorkspaceMemberInvitePathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
  /**
   * Invite Key (secret) for the invited user
   */
  inviteKey: Schemas.InviteKey;
};

export type AcceptWorkspaceMemberInviteError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type AcceptWorkspaceMemberInviteVariables = {
  pathParams: AcceptWorkspaceMemberInvitePathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Accept the invitation to join a workspace. If the operation succeeds the user will be a member of the workspace
 */
export const acceptWorkspaceMemberInvite = (variables: AcceptWorkspaceMemberInviteVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    undefined,
    AcceptWorkspaceMemberInviteError,
    undefined,
    {},
    {},
    AcceptWorkspaceMemberInvitePathParams
  >({ url: '/workspaces/{workspaceId}/invites/{inviteKey}/accept', method: 'post', ...variables, signal });

export type ResendWorkspaceMemberInvitePathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
  /**
   * Invite identifier
   */
  inviteId: Schemas.InviteID;
};

export type ResendWorkspaceMemberInviteError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type ResendWorkspaceMemberInviteVariables = {
  pathParams: ResendWorkspaceMemberInvitePathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * This operation provides a way to resend an Invite notification. Invite notifications can only be sent for Invites not yet accepted.
 */
export const resendWorkspaceMemberInvite = (variables: ResendWorkspaceMemberInviteVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    undefined,
    ResendWorkspaceMemberInviteError,
    undefined,
    {},
    {},
    ResendWorkspaceMemberInvitePathParams
  >({ url: '/workspaces/{workspaceId}/invites/{inviteId}/resend', method: 'post', ...variables, signal });

export type CPGetDatabaseListPathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
};

export type CPGetDatabaseListError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
>;

export type CPGetDatabaseListVariables = {
  pathParams: CPGetDatabaseListPathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * List all databases available in your Workspace.
 */
export const cPGetDatabaseList = (variables: CPGetDatabaseListVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    Schemas.CPListDatabasesResponse,
    CPGetDatabaseListError,
    undefined,
    {},
    {},
    CPGetDatabaseListPathParams
  >({ url: '/workspaces/{workspaceId}/dbs', method: 'get', ...variables, signal });

export type CPCreateDatabasePathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
  /**
   * The Database Name
   */
  dbName: Schemas.DBName;
};

export type CPCreateDatabaseError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
>;

export type CPCreateDatabaseResponse = {
  /**
   * @minLength 1
   */
  databaseName: string;
  branchName?: string;
};

export type CPCreateDatabaseRequestBody = {
  /**
   * @minLength 1
   */
  branchName?: string;
  /**
   * @minLength 1
   */
  region: string;
  ui?: {
    color?: string;
  };
  metadata?: Schemas.BranchMetadata;
};

export type CPCreateDatabaseVariables = {
  body: CPCreateDatabaseRequestBody;
  pathParams: CPCreateDatabasePathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Create Database with identifier name
 */
export const cPCreateDatabase = (variables: CPCreateDatabaseVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    CPCreateDatabaseResponse,
    CPCreateDatabaseError,
    CPCreateDatabaseRequestBody,
    {},
    {},
    CPCreateDatabasePathParams
  >({ url: '/workspaces/{workspaceId}/dbs/{dbName}', method: 'put', ...variables, signal });

export type CPDeleteDatabasePathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
  /**
   * The Database Name
   */
  dbName: Schemas.DBName;
};

export type CPDeleteDatabaseError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type CPDeleteDatabaseVariables = {
  pathParams: CPDeleteDatabasePathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Delete a database and all of its branches and tables permanently.
 */
export const cPDeleteDatabase = (variables: CPDeleteDatabaseVariables, signal?: AbortSignal) =>
  controlPlaneFetch<undefined, CPDeleteDatabaseError, undefined, {}, {}, CPDeleteDatabasePathParams>({
    url: '/workspaces/{workspaceId}/dbs/{dbName}',
    method: 'delete',
    ...variables,
    signal
  });

export type CPGetCPDatabaseMetadataPathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
  /**
   * The Database Name
   */
  dbName: Schemas.DBName;
};

export type CPGetCPDatabaseMetadataError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type CPGetCPDatabaseMetadataVariables = {
  pathParams: CPGetCPDatabaseMetadataPathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Retrieve metadata of the given database
 */
export const cPGetCPDatabaseMetadata = (variables: CPGetCPDatabaseMetadataVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    Schemas.CPDatabaseMetadata,
    CPGetCPDatabaseMetadataError,
    undefined,
    {},
    {},
    CPGetCPDatabaseMetadataPathParams
  >({ url: '/workspaces/{workspaceId}/dbs/{dbName}', method: 'get', ...variables, signal });

export type CPUpdateCPDatabaseMetadataPathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
  /**
   * The Database Name
   */
  dbName: Schemas.DBName;
};

export type CPUpdateCPDatabaseMetadataError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
  | {
      status: 404;
      payload: Responses.SimpleError;
    }
>;

export type CPUpdateCPDatabaseMetadataRequestBody = {
  ui?: {
    /**
     * @minLength 1
     */
    color?: string;
  };
};

export type CPUpdateCPDatabaseMetadataVariables = {
  body?: CPUpdateCPDatabaseMetadataRequestBody;
  pathParams: CPUpdateCPDatabaseMetadataPathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * Update the color of the selected database
 */
export const cPUpdateCPDatabaseMetadata = (variables: CPUpdateCPDatabaseMetadataVariables, signal?: AbortSignal) =>
  controlPlaneFetch<
    Schemas.CPDatabaseMetadata,
    CPUpdateCPDatabaseMetadataError,
    CPUpdateCPDatabaseMetadataRequestBody,
    {},
    {},
    CPUpdateCPDatabaseMetadataPathParams
  >({ url: '/workspaces/{workspaceId}/dbs/{dbName}', method: 'patch', ...variables, signal });

export type ListRegionsPathParams = {
  /**
   * Workspace ID
   */
  workspaceId: Schemas.WorkspaceID;
};

export type ListRegionsError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Responses.BadRequestError;
    }
  | {
      status: 401;
      payload: Responses.AuthError;
    }
>;

export type ListRegionsVariables = {
  pathParams: ListRegionsPathParams;
} & ControlPlaneFetcherExtraProps;

/**
 * List regions available to create a database on
 */
export const listRegions = (variables: ListRegionsVariables, signal?: AbortSignal) =>
  controlPlaneFetch<Schemas.ListRegionsResponse, ListRegionsError, undefined, {}, {}, ListRegionsPathParams>({
    url: '/workspaces/{workspaceId}/regions',
    method: 'get',
    ...variables,
    signal
  });

export const operationsByTag = {
  users: { getUser, updateUser, deleteUser },
  authentication: { getUserAPIKeys, createUserAPIKey, deleteUserAPIKey },
  workspaces: {
    getWorkspacesList,
    createWorkspace,
    getWorkspace,
    updateWorkspace,
    deleteWorkspace,
    getWorkspaceMembersList,
    updateWorkspaceMemberRole,
    removeWorkspaceMember
  },
  invites: {
    inviteWorkspaceMember,
    updateWorkspaceMemberInvite,
    cancelWorkspaceMemberInvite,
    acceptWorkspaceMemberInvite,
    resendWorkspaceMemberInvite
  },
  databases: {
    cPGetDatabaseList,
    cPCreateDatabase,
    cPDeleteDatabase,
    cPGetCPDatabaseMetadata,
    cPUpdateCPDatabaseMetadata,
    listRegions
  }
};
