/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import type * as Schemas from './controlPlaneSchemas';

export type APIKeyNameParam = Schemas.APIKeyName;

export type InviteIDParam = Schemas.InviteID;

export type InviteKeyParam = Schemas.InviteKey;

export type OAuthAccessTokenParam = Schemas.AccessToken;

export type OAuthClientIDParam = Schemas.OAuthClientID;

export type UserIDParam = Schemas.UserID;

export type WorkspaceIDParam = Schemas.WorkspaceID;

export type PageSizeParam = Schemas.PageSize;

export type PageTokenParam = Schemas.PageToken;

export type ClusterIDParam = Schemas.ClusterID;

export type DBNameParam = Schemas.DBName;
