/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import type * as Schemas from './dataPlaneSchemas';

export type DBNameParam = Schemas.DBName;

export type DBBranchNameParam = Schemas.DBBranchName;

export type MigrationRequestNumberParam = Schemas.MigrationRequestNumber;

export type BranchNameParam = Schemas.BranchName;

export type TableNameParam = Schemas.TableName;

export type ColumnNameParam = Schemas.ColumnName;

export type ColumnsProjectionParam = Schemas.ColumnsProjection;

export type RecordIDParam = Schemas.RecordID;

export type FileIDParam = Schemas.FileID;
