/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import type * as Schemas from './dataPlaneSchemas';

export type DBBranchNameParam = Schemas.DBBranchName;

export type TableNameParam = Schemas.TableName;

/**
 * @format date-time
 */
export type TimestampCursorParam = string;

export type LimitParam = Schemas.PaginationPageSize;

export type MigrationJobIDParam = Schemas.MigrationJobID;

export type DBNameParam = Schemas.DBName;

export type MigrationRequestNumberParam = Schemas.MigrationRequestNumber;

export type BranchNameParam = Schemas.BranchName;

export type ColumnNameParam = Schemas.ColumnName;

export type ColumnsProjectionParam = Schemas.ColumnsProjection;

export type RecordIDParam = Schemas.RecordID;

export type FileItemIDParam = Schemas.FileItemID;

/**
 * @maxLength 36
 * @minLength 36
 */
export type ChatSessionIDParam = string;

export type FileAccessIDParam = Schemas.FileAccessID;

export type FileSignatureParam = Schemas.FileSignature;
