/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import type * as Schemas from './schemas';

export type APIKeyNameParam = Schemas.APIKeyName;

export type InviteIDParam = Schemas.InviteID;

export type InviteKeyParam = Schemas.InviteKey;

export type UserIDParam = Schemas.UserID;

export type WorkspaceIDParam = Schemas.WorkspaceID;

export type BranchNameParam = Schemas.BranchName;

export type ColumnNameParam = Schemas.ColumnName;

export type ColumnsProjectionParam = Schemas.ColumnsProjection;

export type DBBranchNameParam = Schemas.DBBranchName;

export type DBNameParam = Schemas.DBName;

export type MigrationRequestNumberParam = Schemas.MigrationRequestNumber;

export type RecordIDParam = Schemas.RecordID;

export type TableNameParam = Schemas.TableName;
