name: Update pgroll spec

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * 1-5' # once every 3 hours on week days

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          cache: 'pnpm'

      - name: Check for pgroll spec updates
        run: cd packages/pgroll && pnpm generate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: 'Update pgroll spec'
          committer: 'Xata Bot 🦋 <xata-bot@users.noreply.github.com>'
          title: 'Update pgroll spec'
          body: |
            This is an autogenerated PR to update the pgroll spec.
          branch: update-pgroll-${{ github.run_id }}
