name: Test Release

on:
  push:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-cli-assets:
    outputs:
      version: ${{ jobs.release-cli-assets.capture-version.outputs.version }}
      mac_intel_sha: ${{ jobs.relase-cli-assets.sha-macos.outputs.sha-macos-intel}},
      mac_arm_sha: ${{ jobs.relase-cli-assets.sha-macos.outputs.sha-macos-arm }}
      linux_sha: ${{ jobs.relase-cli-assets.sha-ubuntu.outputs.sha-linux }},
      linux_arm_sha: ${{ jobs.relase-cli-assets.sha-ubuntu.outputs.sha-linux-arm }}
      id: publish-cli-assets
      name: Publish CLI assets Test
    uses: ./.github/workflows/release-cli-assets.yml
    with:
      publishedPackages: '[{"name": "@xata.io/cli", "version": "0.15.15"}]'
      commitSha: ${{ github.sha }}
    secrets: inherit

  update-homebrew:
    needs: [publish-cli-assets]
    uses: ./.github/workflows/update-homebrew.yml
    with:
      commit_sha: ${{ github.sha }}
      version: ${{ needs.publish-cli-assets.outputs.version }}
      mac_intel_sha: ${{ needs.publish-cli-assets.outputs.mac_intel_sha }}
      mac_arm_sha: ${{ needs.publish-cli-assets.outputs.mac_arm_sha }}
      linux_sha: ${{ needs.publish-cli-assets.outputs.linux_sha }}
      linux_arm_sha: ${{ needs.publish-cli-assets.outputs.linux_arm_sha }}
    secrets: inherit
