name: Test Release

on:
  push:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-homebrew:
    uses: ./.github/workflows/update-homebrew.yml
    with:
      commit_sha: '1'
      version: '2'
      mac_intel_sha: '3'
      mac_arm_sha: '4'
      linux_sha: '5'
      linux_arm_sha: '6'
    secrets: inherit
