name: Test Release

on:
  push:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-cli-assets:
    name: Publish CLI assets Test
    uses: ./.github/workflows/release-cli-assets.yml
    with:
      publishedPackages: '[{"name": "@xata.io/cli", "version": "0.15.15"}]'
      commitSha: ${{ github.sha }}
    secrets: inherit

  update-homebrew:
    needs: [publish-cli-assets]
    uses: ./.github/workflows/update-homebrew.yml
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      commit_sha: ${{ github.sha }}
      version: ${{ needs.release.outputs.version }}
      mac_intel_sha: ${{ needs.publish-cli-assets.outputs.mac_intel_sha }}
      mac_arm_sha: ${{ needs.publish-cli-assets.outputs.mac_arm_sha }}
      linux_sha: ${{ needs.publish-cli-assets.outputs.linux_sha }}
      linux_arm_sha: ${{ needs.publish-cli-assets.outputs.linux_arm_sha }}
    secrets: inherit
