name: Update Homebrew Formula

on:
  workflow_call:
    inputs:
      commit_sha:
        description: 'Commit SHA'
        required: true
        type: string
      version:
        description: 'Latest version'
        required: true
        type: string
      mac_intel_sha:
        description: 'Mac Intel SHA'
        required: true
        type: string
      mac_arm_sha:
        description: 'Mac ARM SHA'
        required: true
        type: string
      linux_sha:
        description: 'Linux SHA'
        required: true
        type: string
      linux_arm_sha:
        description: 'Linux ARM SHA'
        required: true
        type: string

jobs:
  update-homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: xataio/homebrew-brew
          ref: 'main'
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0

      - name: setup git config
        run: |
          git config user.email "system@xata.io"
          git config user.name "Xata"

      - name: Read template file
        id: gettemplate
        run: echo "template=$(cat ./Template/xata.rb)" >> $GITHUB_OUTPUT

      - name: Update Homebrew Formula using template variables
        id: updateformula
        run: |
          echo "${{ steps.gettemplate.outputs.template }}" > ./Formula/xata.rb
          sed -i 's/__CLI_VERSION__/${{ inputs.version }}/g' ./Formula/xata.rb
          sed -i 's/__CLI_MAC_INTEL_SHA256__/${{ inputs.mac_intel_sha }}/g' ./Formula/xata.rb
          sed -i 's/__CLI_MAC_ARM_SHA256__/${{ inputs.mac_arm_sha }}/g' ./Formula/xata.rb
          sed -i 's/__CLI_LINUX_SHA256__/${{ inputs.linux_sha }}/g' ./Formula/xata.rb
          sed -i 's/__CLI_LINUX_ARM_SHA256__/${{ inputs.linux_arm_sha }}/g' ./Formula/xata.rb

          VER="${{inputs.version}}"
          COMMITSHA="${{inputs.commitSha}}"
          COM="$(echo $COMMITSHA | head -c8)"
          BASE_URL="https://xata-cli-assets.s3.us-east-1.amazonaws.com/versions/${VER}/${COM}/xata-v${VER}-${COM}"

          CLI_MAC_INTEL_DOWNLOAD_URL="${BASE_URL}-darwin-x64.tar.xz"
          CLI_MAC_ARM_DOWNLOAD_URL="${BASE_URL}-darwin-arm64.tar.xz"
          CLI_LINUX_DOWNLOAD_URL="${BASE_URL}-linux-x64.tar.xz"
          CLI_LINUX_ARM_DOWNLOAD_URL="${BASE_URL}-linux-arm64.tar.xz"

          sed -i 's/__CLI_MAC_INTEL_DOWNLOAD_URL__/${CLI_MAC_INTEL_DOWNLOAD_URL}/g' ./Formula/xata.rb
          sed -i 's/__CLI_MAC_ARM_DOWNLOAD_URL__/${CLI_MAC_INTEL_DOWNLOAD_URL}/g' ./Formula/xata.rb
          sed -i 's/__CLI_LINUX_DOWNLOAD_URL__/${CLI_MAC_INTEL_DOWNLOAD_URL}/g' ./Formula/xata.rb
          sed -i 's/__CLI_LINUX_ARM_DOWNLOAD_URL__/${CLI_MAC_INTEL_DOWNLOAD_URL}/g' ./Formula/xata.rb

          echo "formula=$(cat ./Formula/xata.rb)" >> $GITHUB_OUTPUT

      - name: Read formula file
        id: getformula
        run: echo ${{ steps.updateformula.outputs.formula }}

      - name: commit changes
        run: |
          git status
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          repository: xataio/homebrew-brew
          force: true
