name: Update next branch with latest main

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-next:
    name: Update next branch with latest main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: |
          git config user.email "system@xata.io"
          git config user.name "Xata"

      - name: Rebase next branch with latest main
        run: |
          git checkout next
          git rebase main
          git push origin next
