name: Update next branch with latest main

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-next:
    name: Update next branch with latest main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes the whole repo to be checked out
          fetch-depth: 0
          # This makes the PR pushed to use GITHUB_TOKEN and trigger the checks
          persist-credentials: false
          token: ${{ secrets.GIT_TOKEN }}

      - name: Configure
        run: |
          git config user.email "system@xata.io"
          git config user.name "Xata"

      - name: Rebase next branch with latest main
        run: |
          git checkout origin/next
          git rebase origin/main
          git push origin HEAD:next -f
